# Generated by Django 5.0.3 on 2024-04-28 11:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('filepath', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.CharField(max_length=8, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Активен', max_length=50)),
            ],
        ),
    ]
