# Generated by Django 5.0.3 on 2024-04-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='media',
            name='filepath',
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='duration',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
