# Generated by Django 5.0.3 on 2024-04-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_remove_media_filename_remove_media_filepath_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(null=True)),
            ],
        ),
    ]
