# Generated by Django 5.0.3 on 2024-04-28 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='django_app.media')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.schedule')),
            ],
        ),
    ]
